name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Fetch tags
        run: git fetch --prune --unshallow

      - name: release dry run
        run: make release-dry-run

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env

      - name: release publish
        run: make release
